[build]
  base = "site"
  command = "hugo"
  publish = "public"

[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[dev]
  framework = "hugo"
  targetPort = 1313

# Agar Cypress plugin chahiye to rakh sakte ho, nahi to hata do.
# Par build ke liye zaroori nahi.
